---
# Playbook format reference: https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_intro.html
# YAML formatting tips for Ansible: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html
- name: Install base packages on dev machines
  hosts: dev
  become: true

  roles:
    - role: user_settings
    - role: general_tools
    - role: software_development
    - role: vivado
